### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [dzheis/skill_up_education#1]
1)
формат текста не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/100711721-5e106b00-33ba-11eb-87db-aa1c98d493a4.png)

2)
высота блоков не соответствует поставленной задаче
![image](https://user-images.githubusercontent.com/8464662/100711892-99ab3500-33ba-11eb-8865-e8176a49cddd.png)

3)
размер текста не соответствует макету, проверяйте для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/100711956-ad569b80-33ba-11eb-82d6-68f160881a19.png)

4)
форма отображается неправильно для некоторых разрешений
![image](https://user-images.githubusercontent.com/8464662/100712022-c3645c00-33ba-11eb-9cfc-ad5c0338b8a1.png)

5)
работа содержит невалидный код
![image](https://user-images.githubusercontent.com/8464662/100712074-dc6d0d00-33ba-11eb-846b-0093ec93b7ac.png)

**Comment by Alecto** [comment]
исправили, кроме ошибки №3

**Comment by dzheis** [comment]
Исправил ошибку №3. Добавил соответствующий коммит.

ср, 2 дек. 2020 г. в 18:41, Andrey <notifications@github.com>:
